trigger:
  batch: true
  tags:
    include:
      - v*

pr: none

resources:
  repositories:
    - repository: self
    - repository: common
      type: git
      name: "Incursor/incursor-back"
      ref: refs/heads/main

variables:
  - template: .cicd/variables/common.yaml@common

stages:
  - template: .cicd/stages/java/cd.yaml@common
